# Generated by Django 5.1.6 on 2025-10-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='default',
        ),
        migrations.AddField(
            model_name='gym',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gym',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
