# Generated by Django 5.1.6 on 2025-08-31 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_rename_user_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='auth0_sub',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
