# Generated by Django 5.1.6 on 2025-10-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_gym_default_gym_country_gym_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='icon',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
