# Generated by Django 5.1.6 on 2025-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_gym_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.JSONField(default=dict),
        ),
    ]
