# Generated by Django 5.1.6 on 2025-09-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_session_created_at_alter_appuser_auth0_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduling.gym'),
        ),
    ]
